name: Auto-update README Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # كل 5 دقائق

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update README timestamp
        run: |
          echo "Updating README timestamp..."
          TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
          sed -i "s/Last updated: .*/Last updated: $TIMESTAMP/" README.md || echo "Add 'Last updated' line first"

      - name: Optional: Update Pie Chart dynamically
        run: |
          echo "You can run a Python script here to fetch GitHub languages and update QuickChart URL in README"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update README stats" || echo "No changes to commit"
          git push
